[meta]
name = "nord"
author = "arcticicestudio"


[palette]
background = "#2E3440"
foreground = "#D8DEE9"

accent = "#88C0D0"
surface = "#3B4252"

blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"

muted = "#4C566A"
warning = "#D08770"
error = "#BF616A"


[highlight.Normal]
fg = "foreground"
bg = "background"


[highlight.CursorLine]
fg = "foreground"
bg = "surface"


[highlight.LineNr]
fg = "green"
bg = "background"


[highlight.CursorLineNr]
fg = "cyan"
bg = "background"


[highlight.StatusLine]
fg = "background"
bg = "accent"


[highlight.Muted]
fg = "muted"
bg = "background"


[highlight.Warning]
fg = "warning"
bg = "background"


[fillchars]
eob = "~"
