[meta]
name = "tokyo-night"
author = "folke"

[palette]
background = "#1A1B26"
foreground = "#C0CAF5"

accent = "#7AA2F7"
surface = "#24283B"

blue = "#7DCFFF"
green = "#9ECE6A"
purple = "#BB9AF7"

muted = "#565F89"
warning = "#E0AF68"
error = "#F7768E"


[highlight.Normal]
fg = "foreground"
bg = "background"

[highlight.CursorLine]
fg = "foreground"
bg = "surface"

[highlight.LineNr]
fg = "muted"
bg = "background"

[highlight.CursorLineNr]
fg = "blue"
bg = "background"

[highlight.StatusLine]
fg = "background"
bg = "accent"

[highlight.Muted]
fg = "muted"
bg = "background"

[highlight.Warning]
fg = "warning"
bg = "background"


[fillchars]
eob = "~"
