[meta]
name = "eternal grey"
author = "unknown"


[palette]
background = "#232427"
foreground = "#D8D8D4"
accent = "#707C8A"
muted = "#7B838C"
warning = "#B85C5C"


[highlight.Normal]
fg = "foreground"
bg = "background"


[highlight.CursorLine]
fg = "background"
bg = "accent"


[highlight.LineNr]
fg = "muted"
bg = "background"


[highlight.CursorLineNr]
fg = "accent"
bg = "background"


[highlight.StatusLine]
fg = "foreground"
bg = "accent"


[highlight.Muted]
fg = "muted"
bg = "background"


[highlight.Warning]
fg = "warning"
bg = "background"


[fillchars]
eob = "~"
