[colors]

bg = "#282828"
fg = "#ebdbb2"

secondary_bg = "#3c3836"
secondary_fg = "#ebdbb2"

statusline_bg = "#98971a"
statusline_fg = "#1d2021"

highlight_bg = "#b8bb26"
highlight_fg = "#1d2021"

index_bg = "#458588"
index_fg = "fb1f1c7"
