[meta]
name = "linen"
author = "unknown"

[palette]
background = "#ECE6DA"
foreground = "#38342F"
accent = "#8C9A8E"
muted = "#8B847A"
warning = "#C56B5C"


[highlight.Normal]
fg = "foreground"
bg = "background"

[highlight.CursorLine]
fg = "background"
bg = "accent"

[highlight.LineNr]
fg = "muted"
bg = "background"

[highlight.CursorLineNr]
fg = "accent"
bg = "background"

[highlight.StatusLine]
fg = "foreground"
bg = "accent"

[highlight.Muted]
fg = "muted"
bg = "background"

[highlight.Warning]
fg = "warning"
bg = "background"


[fillchars]
eob = "~"
