[meta]
name = "midnight"
author = "unknown"


[palette]
background = "#181825"
foreground = "#D9E0EE"
accent = "#C792EA"
muted = "#6E6C7E"
warning = "#F38BA8"


[highlight.Normal]
fg = "foreground"
bg = "background"

[highlight.CursorLine]
fg = "background"
bg = "accent"

[highlight.LineNr]
fg = "muted"
bg = "background"

[highlight.CursorLineNr]
fg = "accent"
bg = "background"

[highlight.StatusLine]
fg = "background"
bg = "accent"

[highlight.Muted]
fg = "muted"
bg = "background"

[highlight.Warning]
fg = "warning"
bg = "background"


[fillchars]
eob="~"
