[meta]
name="miku"
author="unknown"


[palette]
background="#232829"
foreground="#DCD7D6"
accent="#7BC6D5"
muted="#7D8899"
warning="#DE2583"


[highlight.Normal]
fg="foreground"
bg="background"

[highlight.CursorLine]
fg="background"
bg="accent"

[highlight.LineNr]
fg="muted"
bg="background"

[highlight.CursorLineNr]
fg="accent"
bg="background"

[highlight.StatusLine]
fg="background"
bg="accent"

[highlight.Muted]
fg="muted"
bg="background"

[highlight.Warning]
fg="warning"
bg="background"


[fillchars]
eob="~"
