[colors]

bg = "#2e3440"
fg = "#d8dee9"

secondary_bg = "#3b4242"
secondary_fg = "#e5e9f0"

statusline_bg = "#88c0d0"
statusline_fg = "#2e3440"

highlight_bg = "#a3be8c"
highlight_fg = "#2e3440"

index_bg = "#81a1c1"
index_fg = "#eceff4"

args_fg = "#a3be8c"
