[meta]
name="nvim"
author="unknown"


[palette]
background="#14161B"
foreground="#D8DAE2"
accent="#A0D9A9"
muted="#4D5056"
warning="#67BED9"


[highlight.Normal]
fg="foreground"
bg="background"


[highlight.CursorLine]
fg="background"
bg="accent"


[highlight.LineNr]
fg="muted"
bg="background"


[highlight.CursorLineNr]
fg="accent"
bg="background"


[highlight.StatusLine]
fg="foreground"
bg="background"


[highlight.Muted]
fg="muted"
bg="background"


[highlight.Warning]
fg="background"
bg="warning"


[fillchars]
eob="~"
