[meta]
name="slate"
author="unknown"


[palette]
background="#181A1B"
foreground="#D2D5D9"
accent="#7B8794"
muted="#69727B"
warning="#C25B68"


[highlight.Normal]
fg="foreground"
bg="background"

[highlight.CursorLine]
fg="background"
bg="accent"

[highlight.LineNr]
fg="muted"
bg="background"

[highlight.CursorLineNr]
fg="accent"
bg="background"

[highlight.StatusLine]
fg="foreground"
bg="accent"

[highlight.Muted]
fg="muted"
bg="background"

[highlight.Warning]
fg="warning"
bg="background"


[fillchars]
eob="~"
