[colors]

bg = "#181A1B"
fg = "#D2D5D9"

secondary_bg = "#7B8794"
secondary_fg = "#F8F9FA"

statusline_bg = "#3B434B"
statusline_fg = "#F8F9FA"

index_bg = "#181A1B"
index_fg = "#69727B"

time_fg = "#69727B"

indicator_line_bg = "#A7B0BA"
indicator_line_fg = "#181A1B"

indicator_num_bg = "#181A1B"
indicator_num_fg = "#A7B0BA"

warning_bg = "#C25B68"
warning_fg = "#FFFFFF"
