[meta]
name="tokyo-night"
author="unknown"


[palette]
background="#1A1B26"
foreground="#C0CAF5"
accent="#7AA2F7"
muted="#565F89"
warning="#F7768E"


[highlight.Normal]
fg="foreground"
bg="background"

[highlight.CursorLine]
fg="background"
bg="accent"

[highlight.LineNr]
fg="muted"
bg="background"

[highlight.CursorLineNr]
fg="accent"
bg="background"

[highlight.StatusLine]
fg="foreground"
bg="accent"

[highlight.Muted]
fg="muted"
bg="background"

[highlight.Warning]
fg="warning"
bg="background"


[fillchars]
eob="~"
