[meta]
name="warm"
author="unknown"


[palette]
background="#EEE7DD"
foreground="#38342F"
accent="#A67C52"
muted="#93897D"
warning="#C75C5C"


[highlight.Normal]
fg="foreground"
bg="background"

[highlight.CursorLine]
fg="background"
bg="accent"

[highlight.LineNr]
fg="muted"
bg="background"

[highlight.CursorLineNr]
fg="accent"
bg="background"

[highlight.StatusLine]
fg="background"
bg="accent"

[highlight.Muted]
fg="muted"
bg="background"

[highlight.Warning]
fg="warning"
bg="background"


[fillchars]
eob="~"
