[meta]
name = "dracula"
author = "dracula"

[palette]
background = "#282A36"
foreground = "#F8F8F2"

accent = "#BD93F9"
surface = "#44475A"

purple = "#BD93F9"
cyan = "#8BE9FD"
green = "#50FA7B"

muted = "#6272A4"
warning = "#FFB86C"
error = "#FF5555"

[highlight.Normal]
fg = "foreground"
bg = "background"

[highlight.CursorLine]
fg = "foreground"
bg = "surface"

[highlight.LineNr]
fg = "muted"
bg = "background"

[highlight.CursorLineNr]
fg = "cyan"
bg = "background"

[highlight.StatusLine]
fg = "background"
bg = "purple"

[highlight.Muted]
fg = "muted"
bg = "background"

[highlight.Warning]
fg = "warning"
bg = "background"

[fillchars]
eob = "~"
