[meta]
name = "catppuccin-mocha"
author = "catppuccin"

[palette]
background = "#1E1E2E"
foreground = "#CDD6F4"
accent = "#CBA6F7"

surface = "#313244"

blue = "#89B4FA"
green = "#A6E3A1"
yellow = "#F9E2AF"

muted = "#6C7086"
warning = "#FAB387"
error = "#F38BA8"

[highlight.CursorBlock]
fg = "background"
bg = "blue"

[highlight.Normal]
fg = "foreground"
bg = "background"

[highlight.CursorLine]
fg = "foreground"
bg = "surface"

[highlight.LineNr]
fg = "green"
bg = "background"

[highlight.CursorLineNr]
fg = "accent"
bg = "surface"

[highlight.StatusLine]
fg = "background"
bg = "blue"

[highlight.Muted]
fg = "muted"
bg = "background"

[highlight.Warning]
fg = "warning"
bg = "background"

[fillchars]
eob = "~"
