[meta]
name = "nvim"
author = "Vi-Player"

[palette]
background = "#14161B"
foreground = "#D8DAE2"

accent = "#A0D9A9"
surface = "#20242B"

green = "#A0D9A9"
blue = "#67BED9"
cyan = "#7DCFFF"

muted = "#4D5056"
warning = "#67BED9"
error = "#E06C75"

[highlight.Normal]
fg = "foreground"
bg = "background"

[highlight.CursorBlock]
fg = "background"
bg = "cyan"

[highlight.CursorLine]
fg = "foreground"
bg = "surface"

[highlight.LineNr]
fg = "muted"
bg = "background"

[highlight.CursorLineNr]
fg = "accent"
bg = "background"

[highlight.StatusLine]
fg = "foreground"
bg = "surface"

[highlight.Muted]
fg = "muted"
bg = "background"

[highlight.Warning]
fg = "background"
bg = "warning"

[fillchars]
eob = "~"

