[meta]
name = "rose-pine"
author = "rose-pine"

[palette]
background = "#191724"
foreground = "#E0DEF4"

accent = "#C4A7E7"
surface = "#26233A"

rose = "#EBBCBA"
foam = "#9CCFD8"
pine = "#31748F"

muted = "#6E6A86"
warning = "#F6C177"


[highlight.Normal]
fg = "foreground"
bg = "background"

[highlight.CursorBlock]
fg = "background"
bg = "foam"

[highlight.CursorLine]
fg = "foreground"
bg = "surface"

[highlight.LineNr]
fg = "muted"
bg = "background"

[highlight.CursorLineNr]
fg = "foam"
bg = "background"

[highlight.StatusLine]
fg = "background"
bg = "accent"

[highlight.Muted]
fg = "pine"
bg = "background"

[highlight.Warning]
fg = "warning"
bg = "background"


[fillchars]
eob = "~"

